development:
  adapter: mysql2
  database: linktag_development
  pool: 5
  username: root
  password: qburst
  host: localhost
  
staging:
  adapter: mysql2
  database: atlas_claims_staging
  pool: 5
  username: root
  password: matrixreloaded
  host: atlasclaim.cuehadg7hl61.us-west-2.rds.amazonaws.com
  
production:
  adapter: mysql2
  database: atlas_claims_production
  pool: 5
  username: root
  password: matrixreloaded
  host: atlasclaim.cuehadg7hl61.us-west-2.rds.amazonaws.com
