development:
  adapter: mysql2
  database: linktag_development
  pool: 5
  username: 
  password: 
  host: 
  
staging:
  adapter: mysql2
  database: 
  pool: 5
  username: 
  password: 
  host: 
  
production:
  adapter: mysql2
  database: 
  pool: 5
  username: 
  password: 
  host: 
